# Generated by Django 5.0 on 2024-04-04 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nascimento', models.DateField(verbose_name='Data de Nas cimento')),
                ('contatos_estabelecidos', models.IntegerField(verbose_name='Contatos estabelecidos')),
                ('negocios_realizados', models.IntegerField(verbose_name='Negócios realizados')),
            ],
        ),
        migrations.CreateModel(
            name='AgendarEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField(verbose_name='Data de Envio')),
                ('send_time', models.TimeField(verbose_name='Hora de Envio')),
                ('email_template', models.TextField(verbose_name='Template do E-mail')),
                ('enviado', models.BooleanField(default=False, verbose_name='Mensagem Enviada')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.contatos', verbose_name='Nome')),
            ],
        ),
    ]
