# Generated by Django 5.0 on 2024-04-05 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('arquivo', models.FileField(upload_to='uploads_html/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html'])], verbose_name='Arquivo HTML')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
            ],
        ),
    ]
