# Generated by Django 5.0 on 2024-04-10 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_uploadtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaremail',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.uploadtemplate', verbose_name='Template do E-mail'),
        ),
    ]
