# Generated by Django 5.0 on 2024-04-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_agendaremail_email_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaremail',
            name='nome',
        ),
        migrations.AddField(
            model_name='agendaremail',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emails.contatos', verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
