# Generated by Django 5.0 on 2024-04-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_remove_agendaremail_nome_agendaremail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaremail',
            name='assunto',
            field=models.CharField(default=0, max_length=255, verbose_name='Assunto'),
            preserve_default=False,
        ),
    ]
