# Generated by Django 5.0 on 2024-04-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_agendaremail_assunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaremail',
            name='periodo',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
