# Generated by Django 5.0 on 2024-04-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_agendaremail_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaremail',
            name='repeticao',
            field=models.CharField(choices=[('Não repete', 'Não repete'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendaremail',
            name='periodo',
            field=models.CharField(choices=[('não repete', 'não repete'), ('diário', 'diário'), ('semanal', 'semanal'), ('mensal', 'mensal'), ('enésimo dia útil', 'enésimo dia útil')], max_length=255),
        ),
    ]
