# Generated by Django 5.0 on 2024-04-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_alter_agendaremail_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaremail',
            name='periodo',
            field=models.CharField(choices=[('nao repete', 'não repete'), ('diario', 'diário'), ('semanal', 'semanal'), ('mensal', 'mensal'), ('enesimo dia util', 'enésimo dia útil')], max_length=255, verbose_name='Período'),
        ),
    ]
