# Generated by Django 5.0 on 2024-05-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_alter_agendaremail_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaremail',
            name='conteudo_personaliado',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
