# Generated by Django 5.0 on 2024-05-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_agendaremail_conteudo_personaliado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaremail',
            name='conteudo_personaliado',
        ),
        migrations.AddField(
            model_name='agendaremail',
            name='conteudo_personalizado',
            field=models.JSONField(default=0, verbose_name='Conteúdo personalizado'),
            preserve_default=False,
        ),
    ]
