# Generated by Django 5.1.6 on 2025-03-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0012_alter_contatos_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='faturamento',
            field=models.IntegerField(default=0, verbose_name='Valor faturado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contatos',
            name='lucro',
            field=models.IntegerField(default=0, verbose_name='Valor do lucro'),
            preserve_default=False,
        ),
    ]
