# Generated by Django 5.1.6 on 2025-03-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0014_htmltemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltemplate',
            name='template',
            field=models.TextField(max_length=1000000000),
        ),
    ]
