# Generated by Django 5.0 on 2024-12-16 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microobjetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('nome_objetivomarco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metricas.objetivosmarco')),
            ],
        ),
        migrations.AlterField(
            model_name='computarevolucao',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metricas.microobjetivos'),
        ),
    ]
