# Generated by Django 5.0 on 2024-12-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0002_microobjetivos_alter_computarevolucao_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='microobjetivos',
            name='status',
            field=models.CharField(choices=[('Em Progresso', 'Em Progresso'), ('Concluído', 'Concluído')], default='Em Progresso', max_length=20),
        ),
    ]
