# Generated by Django 5.0 on 2024-12-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0003_microobjetivos_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microobjetivos',
            name='status',
        ),
        migrations.AddField(
            model_name='metasdelongoprazo',
            name='status',
            field=models.CharField(choices=[('Em Progresso', 'Em Progresso'), ('Concluído', 'Concluído')], default='Em Progresso', max_length=20),
        ),
        migrations.AddField(
            model_name='objetivosmarco',
            name='status',
            field=models.CharField(choices=[('Em Progresso', 'Em Progresso'), ('Concluído', 'Concluído')], default='Em Progresso', max_length=20),
        ),
    ]
