# Generated by Django 5.0 on 2024-12-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0004_remove_microobjetivos_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasdelongoprazo',
            name='status',
            field=models.CharField(choices=[('<20%', '<20%'), ('>=20%', '>=20%'), ('Concluído', 'Concluído')], default='<=20%', max_length=20),
        ),
    ]
