# Generated by Django 5.0 on 2024-04-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='link_notbook',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
    ]
