# Generated by Django 5.0 on 2024-05-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0002_conteudo_link_notbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='descricao_ingles',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conteudo',
            name='titulo_ingles',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
