# Generated by Django 5.0 on 2024-05-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0004_lancamentoebook1'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentoebook1',
            name='lancamento',
            field=models.CharField(blank=True),
        ),
    ]
