# Generated by Django 5.0 on 2024-05-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0005_lancamentoebook1_lancamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamentoebook1',
            name='lancamento',
        ),
    ]
