# Generated by Django 5.0 on 2024-05-07 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0006_remove_lancamentoebook1_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentoebook1',
            name='lancamento',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
