# Generated by Django 5.0 on 2024-11-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0007_lancamentoebook1_lancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leituras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumo', models.CharField(max_length=500)),
                ('titulo_ingles', models.CharField(max_length=100)),
                ('resumo_ingles', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=10000)),
            ],
        ),
    ]
