# Generated by Django 5.1.6 on 2025-03-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0008_leituras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('titulo_ingles', models.CharField(max_length=100)),
                ('descricao_ingles', models.CharField(max_length=500)),
                ('link_imagem', models.CharField(max_length=10000)),
                ('valor', models.CharField(max_length=500)),
            ],
        ),
    ]
