# Generated by Django 5.0 on 2024-05-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_newsletter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
    ]
