# Generated by Django 5.0 on 2024-05-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_contato_respondido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_created=True)),
                ('ip', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
