# Generated by Django 5.0 on 2024-05-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_visitantes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitantes',
        ),
    ]
